Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import math

In [3]:
n = int (input())
a = np.arange(n, -1, -1)
a

4


array([4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = int (input())
b = np.diag(np.arange(n, -1, -1), k=0)
b

4


array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [5]:
d = np.diagonal(b)
d

array([4, 3, 2, 1, 0])

In [6]:
sum(d)

10

In [7]:
np.trace(b)

10

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [8]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4] ]) 

In [9]:
b = np.array([4, 12, -3])


In [10]:
from numpy import linalg

In [11]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [12]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [19]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [20]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [22]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [23]:
most_similar_user_index = 0
most_similar_cosine = -1.0

for i, us in enumerate(users_stats):
    cur_cosine = cosine(us, next_user_stats)
    if cur_cosine > most_similar_cosine:
        most_similar_cosine = cur_cosine
        most_similar_user_index = i

print(most_similar_user_index, users_stats[most_similar_user_index], most_similar_cosine)

7 [0 1 1 0 0 0] 0.9486832980505138
